require("yeyee-mbpro-m2.plugins.packer")
require("yeyee-mbpro-m2.plugins.nvim-tree")
require("yeyee-mbpro-m2.plugins.todo-comments")
require("yeyee-mbpro-m2.plugins.telescope")
require("yeyee-mbpro-m2.plugins.dashboard")
require("yeyee-mbpro-m2.plugins.gitsigns")
require("yeyee-mbpro-m2.plugins.tint")
require("yeyee-mbpro-m2.plugins.formatter")
